### ISSUE TITLE
Building escons (not installing wheel from pypi), every attempt a failure, ridiculous trace back

### ISSUE THREAD

**Issue by goodwillcoding** [dholth/enscons#25]
What I would call a completely useless traceback ->

```
$ pip install enscons --no-binary :all: --no-cache
Collecting enscons
  Downloading enscons-0.28.0.tar.gz (18 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 2
  ╰─> [53 lines of output]
      Collecting pytoml>=0.1
        Using cached pytoml-0.1.21.tar.gz (8.8 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting enscons>=0.23
        Using cached enscons-0.28.0.tar.gz (18 kB)
      ERROR: Exception:
      Traceback (most recent call last):
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
          status = run_func(*args)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/cli/req_command.py", line 205, in wrapper
          return func(self, options, args)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/commands/install.py", line 339, in run
          requirement_set = resolver.resolve(
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
          result = self._result = resolver.resolve(
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
          state = resolution.resolve(requirements, max_rounds=max_rounds)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
          self._add_to_criteria(self.state.criteria, r, parent=None)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
          if not criterion.candidates:
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
          return bool(self._sequence)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
          return any(self)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
          return (c for c in iterator if id(c) not in self._incompatible_ids)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
          candidate = func()
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
          self._link_candidate_cache[link] = LinkCandidate(
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
          super().__init__(
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
          self.dist = self._prepare()
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
          dist = self._prepare_distribution()
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
          return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
          return self._prepare_linked_requirement(req, parallel_builds)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/operations/prepare.py", line 556, in _prepare_linked_requirement
          dist = _get_prepared_distribution(
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/operations/prepare.py", line 57, in _get_prepared_distribution
          with req_tracker.track(req):
        File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
          return next(self.gen)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/req/req_tracker.py", line 122, in track
          self.add(req)
        File "/tmp/pip-standalone-pip-2i33t5dl/__env_pip__.zip/pip/_internal/req/req_tracker.py", line 92, in add
          raise LookupError(message)
      LookupError: https://files.pythonhosted.org/packages/75/5b/cbcdc336233169cd4133a0155f9c61745350cb2869ca22bd8d402297f257/enscons-0.28.0.tar.gz#sha256=a5d78e7cb367e336cd020743be2fae984293b0c573d8864c750d984635468a93 (from https://pypi.org/simple/enscons/) is already being built: enscons from https://files.pythonhosted.org/packages/75/5b/cbcdc336233169cd4133a0155f9c61745350cb2869ca22bd8d402297f257/enscons-0.28.0.tar.gz#sha256=a5d78e7cb367e336cd020743be2fae984293b0c573d8864c750d984635468a93
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 2
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by goodwillcoding** [comment]
Also I saw this in pyproject.toml
https://github.com/dholth/enscons/blob/master/pyproject.toml#L3
```
[build-system]
build-backend = "enscons.api"
requires = ["pytoml>=0.1", "enscons>=0.23"]
```

So the requirement to build enscons to have enscons install ... I mean that speaks for itself.

**Comment by dholth** [comment]
It should work without `enscons` in the requires line. In the past we built `enscons` with older wheels of itself, much as you would bootstrap a compiler.

**Comment by stanislavlevin** [comment]
@dholth, hello.
For self-hosted build backend `backend-path` is mandatory:
https://peps.python.org/pep-0517/#in-tree-build-backends

for example, build fails with:
```console
[builder@localhost enscons]$ python -m build .
* Creating virtualenv isolated environment...
* Installing packages in isolated environment... (pytoml>=0.1)
* Getting dependencies for sdist...

Traceback (most recent call last):
  File "/usr/src/alt/alt_pyproject/.tox/integration/lib/python3/site-packages/pep517/wrappers.py", line 332, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/usr/src/alt/alt_pyproject/.tox/integration/lib/python3/site-packages/pep517/in_process/_in_process.py", line 89, in _build_backend
    obj = import_module(mod_path)
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'enscons'

ERROR Backend 'enscons.api' is not available.

```
